name: time_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^12.0.1
  intl: ^0.18.0
  local_preferences_api:
    path: packages/local_preferences_api
  local_timer_api:
    path: packages/local_timer_api
  preferences_repository:
    path: packages/preferences_repository
  timer_repository:
    path: packages/timer_repository

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
