name: local_timer_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  drift: ^2.13.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  sqlite3_flutter_libs: ^0.5.18
  timer_api:
    path: ../timer_api
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
